name: manage-azure-policy-bb2b3b48
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Configure_Azure_PaaS_services_to_use_private_DNS_zones_Deploy-Private-DNS-Zones/**'
#      - .github/workflows/manage-azure-policy-bb2b3b48.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_bb2b3b48}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Configure_Azure_PaaS_services_to_use_private_DNS_zones_Deploy-Private-DNS-Zones/**
